// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArlWvSfUqBxHHPe1kx4tGY3Ltc6VvJYNc',
    appId: '1:894708882238:web:9aafe945a8242936edaa6f',
    messagingSenderId: '894708882238',
    projectId: 'ai-meal-planner-b1713',
    authDomain: 'ai-meal-planner-b1713.firebaseapp.com',
    storageBucket: 'ai-meal-planner-b1713.firebasestorage.app',
    measurementId: 'G-BW3LXNQ6R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwrX8KvDWnymLCMUQvl_paPVYhmKGlpNg',
    appId: '1:894708882238:android:7451f62e08411269edaa6f',
    messagingSenderId: '894708882238',
    projectId: 'ai-meal-planner-b1713',
    storageBucket: 'ai-meal-planner-b1713.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNFcAE842_Q-0qN6BdM9f2dgJW7N_Rxy8',
    appId: '1:894708882238:ios:a5ceac192c1c4ddbedaa6f',
    messagingSenderId: '894708882238',
    projectId: 'ai-meal-planner-b1713',
    storageBucket: 'ai-meal-planner-b1713.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNFcAE842_Q-0qN6BdM9f2dgJW7N_Rxy8',
    appId: '1:894708882238:ios:a5ceac192c1c4ddbedaa6f',
    messagingSenderId: '894708882238',
    projectId: 'ai-meal-planner-b1713',
    storageBucket: 'ai-meal-planner-b1713.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArlWvSfUqBxHHPe1kx4tGY3Ltc6VvJYNc',
    appId: '1:894708882238:web:d9f7baab1be9d175edaa6f',
    messagingSenderId: '894708882238',
    projectId: 'ai-meal-planner-b1713',
    authDomain: 'ai-meal-planner-b1713.firebaseapp.com',
    storageBucket: 'ai-meal-planner-b1713.firebasestorage.app',
    measurementId: 'G-6NNTRF83Z6',
  );
}
